FROM centos:7

RUN yum -y update && \
    yum repolist all && \
    yum -y install epel-release && \
    yum-config-manager --enable epel && \
    yum -y groupinstall "Development Tools" && \
    yum -y install \
        zsh \
        vim \
        wget \
        net-tools \
        lsof \
        xauth \
        libxrender-devel \
        gimp \
        sudo \
        zstd \
        openssh-server && \
    yum -y clean all

RUN mkdir /run/sshd

RUN echo AddressFamily inet >> /etc/ssh/sshd_config

RUN echo '%wheel ALL=(ALL:ALL) NOPASSWD:ALL' >> /etc/sudoers
RUN useradd -m -s /usr/bin/zsh -g users -G wheel,adm rhara
RUN echo 'root:password' | chpasswd
RUN echo 'rhara:password' | chpasswd

RUN mkdir /home/rhara/.ssh
COPY authorized_keys /home/rhara/.ssh/authorized_keys
RUN chmod 600 /home/rhara/.ssh/authorized_keys
RUN chown -R rhara:users /home/rhara/.ssh
COPY zshrc /home/rhara/.zshrc
RUN chown rhara:users /home/rhara/.zshrc

EXPOSE 22

USER rhara
WORKDIR /home/rhara

RUN wget -c -q -P /tmp https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
RUN bash /tmp/Miniconda3-latest-Linux-x86_64.sh -b

ENV CONDA_BASE_PREFIX /home/rhara/miniconda3

ENV PATH $CONDA_BASE_PREFIX/bin:$CONDA_BASE_PREFIX/condabin:$PATH
RUN conda create -n chem36 python=3.6 -y

ENV PATH $CONDA_BASE_PREFIX/envs/chem36/bin:$PATH
ENV CONDA_EXE $CONDA_BASE_PREFIX/bin/conda
ENV CONDA_PYTHON_EXE $CONDA_BASE_PREFIX/bin/python
ENV CONDA_SHLVL=1
ENV CONDA_PREFIX $CONDA_BASE_PREFIX/envs/chem36
ENV CONDA_DEFAULT_ENV chem36

RUN conda upgrade -y --all -n base -c default && \
    conda upgrade -y --all -c default && \
    conda install -y \
        psutil \
        numpy \
        scipy \
        scikit-learn \
        pandas \
        scikit-image \
        jupyter \
        notebook \
        bokeh \
        ujson \
        tqdm && \
    conda install -y -c rdkit rdkit && \
    conda install -y -c omnia pdbfixer && \
    conda install -y -c conda-forge \
        py3dmol \
        apsw
RUN pip install -y prody mmpdb


USER root
WORKDIR /root
